# ===========================================
# CONFIGURACOES GERAIS DA APLICACAO
# ===========================================
spring.application.name=recicle-ai
spring.security.enabled=false

# ===========================================
# CONFIGURACAO DO BANCO DE DADOS POSTGRESQL
# ===========================================
spring.datasource.url=jdbc:postgresql://206.42.20.217:5432/reciclaai
spring.datasource.username=avelino
spring.datasource.password=Dimas123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# CONFIGURACAO DO JPA / HIBERNATE
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================================
# CONFIGURACOES OPCIONAIS (CONSOLA H2 DESATIVADA)
# ===========================================
spring.h2.console.enabled=false

# ===========================================
# CONFIGURACOES DO SERVIDOR
# ===========================================
server.port=33444
